#!/bin/sh

##########################################
# copy this script to your thesis folder #
# place in .git/hooks/pre-push           #
##########################################

# If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote="$1"
url="$2"

if [ -f $HOME/git_repos/how-is-your-thesis-going/update_word_count.sh ]; then
    echo "Updating Word Count"
    cd $HOME/git_repos/how-is-your-thesis-going/
    bash update_word_count.sh
    git add data_raw.csv data.csv
    echo "Pushing to site"
    git commit -m "update word count"
    git push
fi
exit 0
